name: navegacao
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.3
  packages:
    path: ./packages
  pedidos:
    path: ./pedidos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
